#- name: My first play
#  hosts: virtualmachines
#  tasks:
#   - name: Ping my hosts
#     ansible.builtin.ping:
#   - name: Print message
#     ansible.builtin.debug:
#       msg: Hello world
#   - name: Install apache httpd  (state=present is optional)
#     ansible.builtin.apt:
#     name: apache2
#     state: present
#d

  #  vars_prompt:
  #
  #    - name: username
  #      prompt: What is your username?
  #      private: no
  #
  #    - name: password
  #      prompt: What is your password?
  #
  #  vars_files:
  #  - "./vars/myvars.yml"
---
- hosts: nodeA
  vars_files: group_vars/all/centosa.yml
  remote_user: jesus
  become: yes
  become_user: piero
    #  become_method: su
    #ansible_become_password: piero #"{{ userpwd }}"
  tasks:
     - name: Create Folder
       path: /srv/www/
       owner: piero #"{{ userpwd }}"
       mode: 0755
       state: directory
       recurse: yes
